development:
  adapter: mysql
  database: radiant_dev
  username: replace-with-your-username
  password: replace-with-your-password
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: radiant_test
  username: replace-with-your-username
  password: replace-with-your-password
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: radiant_production
  username: replace-with-your-username
  password: replace-with-your-password
  socket: /tmp/mysql.sock